"""Схема БД и миграции."""
from __future__ import annotations

import logging

from app.database.connection import db

logger = logging.getLogger('db')


# --------------------------------------------------------------------------- #
# Схема: ID Discord — BIGINT, пароли — TEXT (PBKDF2-хеши).
# --------------------------------------------------------------------------- #
SCHEMA_STATEMENTS = [
    """CREATE TABLE IF NOT EXISTS users (
        id BIGINT,
        name_discord VARCHAR(50),
        song VARCHAR(255),
        password TEXT,
        last_login DATE,
        login VARCHAR(50),
        servers TEXT
    )""",
    """CREATE TABLE IF NOT EXISTS session (
        id BIGINT,
        hash VARCHAR(64),
        expires TEXT
    )""",
    """CREATE TABLE IF NOT EXISTS rights (
        id TEXT,
        name TEXT,
        "desc" TEXT
    )""",
    """CREATE TABLE IF NOT EXISTS users_rights (
        id SERIAL PRIMARY KEY,
        id_right TEXT,
        id_user BIGINT
    )""",
    """CREATE TABLE IF NOT EXISTS messages (
        id BIGINT NOT NULL,
        id_user BIGINT NOT NULL,
        date TEXT NOT NULL,
        id_channel BIGINT NOT NULL,
        content TEXT,
        id_guild BIGINT,
        guild_name TEXT
    )""",
    """CREATE TABLE IF NOT EXISTS user_actions (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        id_user BIGINT NOT NULL,
        id_guild BIGINT,
        guild_name TEXT,
        action VARCHAR(50) NOT NULL,
        target_id BIGINT,
        target_name VARCHAR(50),
        details TEXT,
        date TIMESTAMPTZ NOT NULL DEFAULT now()
    )""",
    """CREATE TABLE IF NOT EXISTS destiny_challenges (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        item_hash BIGINT NOT NULL UNIQUE,
        item_name TEXT,
        solo_challenge TEXT,
        team_challenge TEXT,
        notes TEXT
    )""",
    """CREATE TABLE IF NOT EXISTS destiny_games (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        lobby_id TEXT NOT NULL,
        name TEXT,
        owner_id BIGINT,
        owner_name TEXT,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        ended_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        results JSONB NOT NULL DEFAULT '[]'::jsonb
    )""",
]


def ensure_schema() -> None:
    """Создаёт таблицы (если их нет) и применяет лёгкие миграции."""
    with db() as conn:
        cur = conn.cursor()
        for stmt in SCHEMA_STATEMENTS:
            cur.execute(stmt)
        # Миграции для уже существующих таблиц (PostgreSQL 9.6+).
        cur.execute('ALTER TABLE session ADD COLUMN IF NOT EXISTS expires TEXT')
        cur.execute('ALTER TABLE users ADD COLUMN IF NOT EXISTS servers TEXT')
        # Привязка Bungie.net OAuth: membershipId Destiny 2, тип платформы
        # (3 = Steam) и имя игрока. Плюс токены OAuth (для запросов к API).
        cur.execute(
            'ALTER TABLE users ADD COLUMN IF NOT EXISTS bungie_membership_id '
            'BIGINT')
        cur.execute(
            'ALTER TABLE users ADD COLUMN IF NOT EXISTS bungie_membership_type '
            'INTEGER')
        cur.execute(
            'ALTER TABLE users ADD COLUMN IF NOT EXISTS bungie_name TEXT')
        cur.execute(
            'ALTER TABLE users ADD COLUMN IF NOT EXISTS bungie_access_token '
            'TEXT')
        cur.execute(
            'ALTER TABLE users ADD COLUMN IF NOT EXISTS bungie_refresh_token '
            'TEXT')
        cur.execute(
            'ALTER TABLE users ADD COLUMN IF NOT EXISTS bungie_token_expires '
            'TEXT')


        cur.execute('ALTER TABLE messages ADD COLUMN IF NOT EXISTS content TEXT')

        # Таблица destiny_items упразднена: данные предметов берутся из
        # локального манифеста (app.site.bungie.items). Сначала снимаем FK
        # с destiny_challenges, затем удаляем саму таблицу (если осталась).
        cur.execute(
            'ALTER TABLE destiny_challenges DROP CONSTRAINT IF EXISTS '
            'destiny_challenges_item_hash_fkey')
        cur.execute('DROP TABLE IF EXISTS destiny_items')

        cur.execute(
            'ALTER TABLE messages ADD COLUMN IF NOT EXISTS id_guild BIGINT')
        cur.execute(
            'ALTER TABLE messages ADD COLUMN IF NOT EXISTS guild_name TEXT')
        cur.execute(
            'ALTER TABLE user_actions ADD COLUMN IF NOT EXISTS guild_name TEXT')
        cur.execute(
            'CREATE INDEX IF NOT EXISTS idx_session_hash ON session(hash)')
        cur.execute(
            'CREATE INDEX IF NOT EXISTS idx_users_rights_user '
            'ON users_rights(id_user)')
        cur.execute(
            'CREATE INDEX IF NOT EXISTS idx_messages_user '
            'ON messages(id_user)')
        cur.execute(
            'CREATE INDEX IF NOT EXISTS idx_user_actions_date '
            'ON user_actions(date DESC)')
        cur.execute(
            'CREATE INDEX IF NOT EXISTS idx_user_actions_user '
            'ON user_actions(id_user)')

        # Нужен для ON CONFLICT в OAuth-входе и log_message;
        # при дубликатах — только предупреждаем.
        try:
            cur.execute(
                'CREATE UNIQUE INDEX IF NOT EXISTS idx_users_id_unique '
                'ON users(id)')
        except Exception as exc:
            logger.warning(
                'Не удалось создать уникальный индекс на users.id: %s. '
                'Проверьте БД на дубликаты id.', exc)
        try:
            cur.execute(
                'CREATE UNIQUE INDEX IF NOT EXISTS idx_messages_id_unique '
                'ON messages(id)')
        except Exception as exc:
            logger.warning(
                'Не удалось создать уникальный индекс на messages.id: %s. '
                'Проверьте БД на дубликаты id.', exc)

        cur.close()
